-- $Id: ud.params.lua 3171 2008-11-06 09:06:29Z det $
local intMap = {
  buildAngle               = true, -- udTable -- buildAngle --
  buildingGroundDecalSizeX = true, -- udTable -- buildingGroundDecalSizeX --
  buildingGroundDecalSizeY = true, -- udTable -- buildingGroundDecalSizeY --
  cobID                    = true, -- udTable -- cobID --
  flankingBonusMode        = true, -- udTable -- flankingBonusMode --
  flareSalvoDelay          = true, -- udTable -- flareSalvoDelay --
  flareSalvoSize           = true, -- udTable -- flareSalvoSize --
  flareTime                = true, -- udTable -- flareTime --
  footprintX               = true, -- udTable -- footprintX --
  footprintZ               = true, -- udTable -- footprintZ --
  highTrajectory           = true, -- udTable -- highTrajectory --
  idleTime                 = true, -- udTable -- idleTime --
  minTransportSize         = true, -- udTable -- minTransportSize --
  pieceTrailCEGRange       = true, -- udTable -- pieceTrailCEGRange --
  radarDistance            = true, -- udTable -- radarDistance --
  radarDistanceJam         = true, -- udTable -- radarDistanceJam --
  seismicDistance          = true, -- udTable -- seismicDistance --
  selfDestructCountdown    = true, -- udTable -- selfDestructCountdown --
  slaveTo                  = true, -- wTable -- slaveTo --
  sonarDistance            = true, -- udTable -- sonarDistance --
  sonarDistanceJam         = true, -- udTable -- sonarDistanceJam --
  transportCapacity        = true, -- udTable -- transportCapacity --
  transportSize            = true, -- udTable -- transportSize --
  transportUnloadMethod    = true, -- udTable -- transportUnloadMethod --
  unitRestricted           = true, -- udTable -- unitRestricted --
}

local boolMap = {
  activateWhenBuilt        = true, -- udTable -- activateWhenBuilt --
  airStrafe                = true, -- udTable -- airStrafe --
  buildRange3D             = true, -- udTable -- buildRange3D --
  builder                  = true, -- udTable -- builder --
  builder                  = true, -- udTable -- builder --
  canAssist                = true, -- udTable -- canAssist --
  canAttack                = true, -- udTable -- canAttack --
  canBeAssisted            = true, -- udTable -- canBeAssisted --
  canBuild                 = true, -- udTable -- canBuild --
  canCapture               = true, -- udTable -- canCapture --
  canDGun                  = true, -- udTable -- canDGun --
  canDropFlare             = true, -- udTable -- canDropFlare --
  canFight                 = true, -- udTable -- canFight --
  canFly                   = true, -- udTable -- canFly --
  canGuard                 = true, -- udTable -- canGuard --
  canHover                 = true, -- udTable -- canHover --
  canLoopbackAttack        = true, -- udTable -- canLoopbackAttack --
  canMove                  = true, -- udTable -- canMove --
  canPatrol                = true, -- udTable -- canPatrol --
  canReclaim               = true, -- udTable -- canReclaim --
  canRepair                = true, -- udTable -- canRepair --
  canRepeat                = true, -- udTable -- canRepeat --
  canRestore               = true, -- udTable -- canRestore --
  canResurrect             = true, -- udTable -- canResurrect --
  canSelfDestruct          = true, -- udTable -- canSelfDestruct --
  canSelfRepair            = true, -- udTable -- canSelfRepair --
  canSubmerge              = true, -- udTable -- canSubmerge --
  cantBeTransported        = true, -- udTable -- cantBeTransported --
  capturable               = true, -- udTable -- capturable --
  collide                  = true, -- udTable -- collide --
  commander                = true, -- udTable -- commander --
  decloakOnFire            = true, -- udTable -- decloakOnFire --
  decloakSpherical         = true, -- udTable -- decloakSpherical --
  factoryHeadingTakeoff    = true, -- udTable -- factoryHeadingTakeoff --
  floater                  = true, -- udTable -- floater --
  fullHealthFactory        = true, -- udTable -- fullHealthFactory --
  hideDamage               = true, -- udTable -- hideDamage --
  holdSteady               = true, -- udTable -- holdSteady --
  hoverAttack              = true, -- udTable -- hoverAttack --
  initCloaked              = true, -- udTable -- initCloaked --
  isAirBase                = true, -- udTable -- isAirBase --
  isFeature                = true, -- udTable -- isFeature --
  isFirePlatform           = true, -- udTable -- isFirePlatform --
  isTargetingUpgrade       = true, -- udTable -- isTargetingUpgrade --
  kamikaze                 = true, -- udTable -- kamikaze --
  leaveTracks              = true, -- udTable -- leaveTracks --
  levelGround              = true, -- udTable -- levelGround --
  noAutoFire               = true, -- udTable -- noAutoFire --
  onoffable                = true, -- udTable -- onoffable --
  pushResistant            = true, -- udTable -- pushResistant --
  reclaimable              = true, -- udTable -- reclaimable --
  releaseHeld              = true, -- udTable -- releaseHeld --
  showNanoFrame            = true, -- udTable -- showNanoFrame --
  showNanoSpray            = true, -- udTable -- showNanoSpray --
  showPlayerName           = true, -- udTable -- showPlayerName --
  smoothAnim               = true, -- udTable -- smoothAnim --
  stealth                  = true, -- udTable -- stealth --
  transportByEnemy         = true, -- udTable -- transportByEnemy --
  upright                  = true, -- udTable -- upright --
  useBuildingGroundDecal   = true, -- udTable -- useBuildingGroundDecal --
}

local floatMap = {
  acceleration             = true, -- udTable -- acceleration --
  airHoverFactor           = true, -- udTable -- airHoverFactor --
  airSightDistance         = true, -- udTable -- airSightDistance --
  autoHeal                 = true, -- udTable -- autoHeal --
  brakeRate                = true, -- udTable -- brakeRate --
  buildCostEnergy          = true, -- udTable -- buildCostEnergy --
  buildCostMetal           = true, -- udTable -- buildCostMetal --
  buildDistance            = true, -- udTable -- buildDistance --
  buildTime                = true, -- udTable -- buildTime --
  buildingGroundDecalDecaySpeed = true, -- udTable -- buildingGroundDecalDecaySpeed --
  captureSpeed             = true, -- udTable -- captureSpeed --
  cloakCost                = true, -- udTable -- cloakCost --
  cloakCostMoving          = true, -- udTable -- cloakCostMoving --
  collisionSphereScale     = true, -- udTable -- collisionSphereScale --
  cruiseAlt                = true, -- udTable -- cruiseAlt --
  damageModifier           = true, -- udTable -- damageModifier --
  drag                     = true, -- udTable -- drag --
  energyMake               = true, -- udTable -- energyMake --
  energyStorage            = true, -- udTable -- energyStorage --
  energyStorage            = true, -- udTable -- energyStorage --
  energyUse                = true, -- udTable -- energyUse --
  extractsMetal            = true, -- udTable -- extractsMetal --
  fallSpeed                = true, -- udTable -- fallSpeed --
  flankingBonusMax         = true, -- udTable -- flankingBonusMax --
  flankingBonusMin         = true, -- udTable -- flankingBonusMin --
  flankingBonusMobilityAdd = true, -- udTable -- flankingBonusMobilityAdd --
  flareDelay               = true, -- udTable -- flareDelay --
  flareEfficiency          = true, -- udTable -- flareEfficiency --
  flareReload              = true, -- udTable -- flareReload --
  frontToSpeed             = true, -- udTable -- frontToSpeed --
  fuelUsage                = true, -- wTable -- fuelUsage --
  idleAutoHeal             = true, -- udTable -- idleAutoHeal --
  kamikazeDistance         = true, -- udTable -- kamikazeDistance --
  loadingRadius            = true, -- udTable -- loadingRadius --
  makesMetal               = true, -- udTable -- makesMetal --
  mass                     = true, -- udTable -- mass --
  maxAcc                   = true, -- udTable -- maxAcc --
  maxAileron               = true, -- udTable -- maxAileron --
  maxAngleDif              = true, -- wTable -- maxAngleDif --
  maxBank                  = true, -- udTable -- maxBank --
  maxDamage                = true, -- udTable -- maxDamage --
  maxElevator              = true, -- udTable -- maxElevator --
  maxFuel                  = true, -- udTable -- maxFuel --
  maxPitch                 = true, -- udTable -- maxPitch --
  maxRepairSpeed           = true, -- udTable -- maxRepairSpeed --
  maxRudder                = true, -- udTable -- maxRudder --
  maxSlope                 = true, -- udTable -- maxSlope --
  maxVelocity              = true, -- udTable -- maxVelocity --
  maxWaterDepth            = true, -- udTable -- maxWaterDepth --
  metalMake                = true, -- udTable -- metalMake --
  metalStorage             = true, -- udTable -- metalStorage --
  metalStorage             = true, -- udTable -- metalStorage --
  metalUse                 = true, -- udTable -- metalUse --
  minAirBasePower          = true, -- udTable -- minAirBasePower --
  minCloakDistance         = true, -- udTable -- minCloakDistance --
  minCollisionSpeed        = true, -- udTable -- minCollisionSpeed --
  minTransportMass         = true, -- udTable -- minTransportMass --
  minWaterDepth            = true, -- udTable -- minWaterDepth --
  myGravity                = true, -- udTable -- myGravity --
  power                    = true, -- udTable -- power --
  reclaimSpeed             = true, -- udTable -- reclaimSpeed --
  refuelTime               = true, -- udTable -- refuelTime --
  repairSpeed              = true, -- udTable -- repairSpeed --
  resurrectSpeed           = true, -- udTable -- resurrectSpeed --
  seismicSignature         = true, -- udTable -- seismicSignature --
  sightDistance            = true, -- udTable -- sightDistance --
  sightDistance            = true, -- udTable -- sightDistance --
  slideTolerance           = true, -- udTable -- slideTolerance --
  speedToFront             = true, -- udTable -- speedToFront --
  terraformSpeed           = true, -- udTable -- terraformSpeed --
  tidalGenerator           = true, -- udTable -- tidalGenerator --
  trackOffset              = true, -- udTable -- trackOffset --
  trackStrength            = true, -- udTable -- trackStrength --
  trackStretch             = true, -- udTable -- trackStretch --
  trackWidth               = true, -- udTable -- trackWidth --
  transportMass            = true, -- udTable -- transportMass --
  turnRadius               = true, -- udTable -- turnRadius --
  turnRate                 = true, -- udTable -- turnRate --
  unitFallSpeed            = true, -- udTable -- unitFallSpeed --
  unloadSpread             = true, -- udTable -- unloadSpread --
  volume                   = true, -- sndFileTable -- volume --
  waterline                = true, -- udTable -- waterline --
  windGenerator            = true, -- udTable -- windGenerator --
  wingAngle                = true, -- udTable -- wingAngle --
  wingDrag                 = true, -- udTable -- wingDrag --
  workerTime               = true, -- udTable -- workerTime --
}

local float3Map = {
  collisionSphereOffset    = true, -- udTable -- collisionSphereOffset --
  flankingBonusDir         = true, -- udTable -- flankingBonusDir --
  flareDropVector          = true, -- udTable -- flareDropVector --
  mainDir                  = true, -- wTable -- mainDir --
  nanoColor                = true, -- udTable -- nanoColor --
}

local stringMap = {
  TEDClass                 = true, -- udTable -- TEDClass --
  badTargetCategory        = true, -- wTable -- badTargetCategory --
  buildPic                 = true, -- udTable -- buildPic --
  buildingGroundDecalType  = true, -- udTable -- buildingGroundDecalType --
  category                 = true, -- udTable -- category --
  category                 = true, -- udTable -- category --
  corpse                   = true, -- udTable -- corpse --
  decoyFor                 = true, -- udTable -- decoyFor --
  description              = true, -- udTable -- description --
  explodeAs                = true, -- udTable -- explodeAs --
  file                     = true, -- sndFileTable -- file --
  filename                 = true, -- udTable -- filename --
  gaia                     = true, -- udTable -- gaia --
  iconType                 = true, -- udTable -- iconType --
  movementClass            = true, -- udTable -- movementClass --
  name                     = true, -- wTable -- name --
  name                     = true, -- udTable -- name --
  noChaseCategory          = true, -- udTable -- noChaseCategory --
  objectName               = true, -- udTable -- objectName --
  onlyTargetCategory       = true, -- wTable -- onlyTargetCategory --
  pieceTrailCEGTag         = true, -- udTable -- pieceTrailCEGTag --
  selfDestructAs           = true, -- udTable -- selfDestructAs --
  trackType                = true, -- udTable -- trackType --
  yardMap                  = true, -- udTable -- yardMap --
}

return {
  intMap    = intMap,
  boolMap   = boolMap,
  floatMap  = floatMap,
  float3Map = float3Map,
  stringMap = stringMap,
}

-- SubTable: 	const LuaTable rootTable = game->defsParser->GetRoot().SubTable("UnitDefs");
-- SubTable: 		LuaTable udTable = rootTable.SubTable(unitName);
-- SubTable: 	LuaTable weaponsTable = udTable.SubTable("weapons");
-- SubTable: 			wTable = weaponsTable.SubTable(w + 1);
-- SubTable: 	LuaTable buildsTable = udTable.SubTable("buildOptions");
-- SubTable: 	LuaTable sfxTable = udTable.SubTable("SFXTypes");
-- SubTable: 	LuaTable expTable = sfxTable.SubTable("explosionGenerators");
-- SubTable: 	LuaTable soundsTable = udTable.SubTable("sounds");
-- SubTable: 	udTable.SubTable("customParams").GetMap(ud.customParams);
-- SubTable: 	LuaTable sndTable = soundsTable.SubTable(soundName);
-- SubTable: 		LuaTable sndFileTable = sndTable.SubTable(i);
